# Generated by Django 4.1.2 on 2022-11-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.CharField(choices=[('https://cmput404-team13.herokuapp.com', 'Team13'), ('https://social-distribution-404.herokuapp.com', 'Team19'), ('https://true-friends-404.herokuapp.com', 'Team12')], default='https://true-friends-404.herokuapp.com', max_length=50, null=True),
        ),
    ]
