# Generated by Django 4.1.2 on 2022-11-24 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
