# Generated by Django 4.1.2 on 2022-11-24 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_post_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='temp_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
