# Generated by Django 4.1.2 on 2022-12-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_post_original_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
