# Generated by Django 4.1.2 on 2022-12-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_post_original_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_author_host',
            field=models.CharField(blank=True, choices=[('https://cmput404-team13.herokuapp.com', 'Team13'), ('https://social-distribution-404.herokuapp.com', 'Team19'), ('https://true-friends-404.herokuapp.com', 'Team12')], max_length=50, null=True),
        ),
    ]
