# Generated by Django 4.1.2 on 2022-11-25 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('network', models.CharField(choices=[('local', 'A True TrueFriends To TrueFriends Friend Request'), ('truefriends_to_team13', 'Friend Request From TrueFriends to the Team 13 Network'), ('team13_to_truefriends', 'Friend Request From the Team 13 Network to TrueFriends'), ('truefriends_to_team19', 'Friend Request From TrueFriends to the Team 19 Network'), ('team19_to_truefriends', 'Friend Request From the Team 19 Network to TrueFriends')], default='local', max_length=64)),
                ('recipient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fr_sender', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fr_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
