# Generated by Django 4.1.2 on 2022-11-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
