# Generated by Django 4.1.2 on 2022-11-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(choices=[('https://cmput404-team13.herokuapp.com', 'Team13'), ('https://social-distribution-404.herokuapp.com', 'Team19'), ('https://true-friends-404.herokuapp.com', 'Team12')], default='Team12', max_length=50),
        ),
    ]
