# Generated by Django 4.1.2 on 2022-12-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_author_github_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(choices=[('https://cmput404-team13.herokuapp.com', 'Team13'), ('https://social-distribution-404.herokuapp.com', 'Team19'), ('https://true-friends-404.herokuapp.com', 'Team12'), ('https://socioecon.herokuapp.com', 'Team10')], default='https://true-friends-404.herokuapp.com', max_length=50),
        ),
    ]
