# Generated by Django 4.1.2 on 2022-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
