# Generated by Django 4.1.2 on 2022-11-24 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False),
        ),
    ]
