# Generated by Django 4.1.2 on 2022-12-08 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(default='comment', editable=False, max_length=7)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=5000)),
                ('contentType', models.CharField(choices=[('text/markdown', 'Common Mark'), ('text/plain', 'UTF-8'), ('application/base64', 'Base 64'), ('image/png;base64', 'Base 64 Embedded PNG'), ('image/jpeg;base64', 'Base 64 Embedded JPEG')], default='text/plain', max_length=100)),
            ],
        ),
    ]
