# Generated by Django 4.1.2 on 2022-11-28 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
