# Generated by Django 4.1.2 on 2022-11-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_remove_comment_id_alter_comment_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='temp_id',
            new_name='id',
        ),
    ]
