# Generated by Django 4.1.2 on 2022-10-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(editable=False, max_length=4, verbose_name='post')),
                ('title', models.CharField(default='Untitled', max_length=30, unique=True)),
                ('source', models.URLField(default='', max_length=100)),
                ('origin', models.URLField(default='', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('contentType', models.CharField(choices=[('text/markdown', 'Common Mark'), ('text/plain', 'UTF-8'), ('application/base64', 'Base 64'), ('image/png;base64', 'Base 64 Embedded PNG'), ('image/jpeg;base64', 'Base 64 Embedded JPEG')], max_length=100)),
                ('content', models.TextField()),
                ('categories', models.CharField(blank=True, max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('comments', models.URLField(default='', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS')], default='PUBLIC', max_length=100)),
                ('unlisted', models.BooleanField(default=False)),
            ],
        ),
    ]
