# Generated by Django 4.1.2 on 2022-10-25 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 25, 0, 35, 50, 186029, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS')], default='PUBLIC', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=30, unique=True),
        ),
    ]
