# Generated by Django 4.1.2 on 2022-10-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=30, unique=True),
        ),
    ]
