# Generated by Django 4.1.2 on 2022-10-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
        ('Inbox', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(blank=True, to='Post.post'),
        ),
    ]
