# Generated by Django 4.1.2 on 2022-10-28 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FriendRequest', '0003_friendrequest_receiver_alter_friendrequest_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='type',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='recipient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fr_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fr_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
